### PR TITLE
feat: migrate metadata decoding to protobuf

### PR DESCRIPTION
**Pull request by kruskall**
This should be the last big PR related to protobuf.

Migrate metadata decoding to protobuf and update the code.
Fix a big in rum decoding setting the wrong timestamp
Disable reflection tests again, they are currently broken. (we really should move away from this) 

Related to https://github.com/elastic/apm-data/issues/52

### CODE REVIEW

**Comment by axw** [comment]
> Disable reflection tests again, they are currently broken. (we really should move away from this)

Are they disabled? It doesn't look like it. Did you revert a change, and forget to update the description?
(I don't think we should disable them until we have replacement coverage.)

I just ran the tests locally and got this panic:

```
=== RUN   TestConcurrentAsync/semaphore_empty                                                                                                                                                                                                                                     
panic: assignment to entry in nil map                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                  
goroutine 180 [running]:                                                                                                                                                                                                                                                          
github.com/elastic/apm-data/model/modelpb.Labels.Set(...)                                                                                                                                                                                                                         
        /home/andrew/projects/apm-data/model/modelpb/labels.go:27                                                                        
github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/modeldecoderutil.MergeLabels(0x0?, 0xc000170f00)                      
        /home/andrew/projects/apm-data/input/elasticapm/internal/modeldecoder/modeldecoderutil/labels.go:57 +0x205                       
github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/modeldecoderutil.GlobalLabelsFrom(0xffffffffffffffff?, 0xc000170f00)  
        /home/andrew/projects/apm-data/input/elasticapm/internal/modeldecoder/modeldecoderutil/labels.go:32 +0xa5                        
github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.mapToMetadataModel(0xc00026c480, 0xc000170f00)                     
        /home/andrew/projects/apm-data/input/elasticapm/internal/modeldecoder/v2/decoder.go:576 +0x3a9                                   
github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.decodeMetadata(0xe3ac00, {0xf0a220, 0xc00064e010}, 0xc00014e000?)  
        /home/andrew/projects/apm-data/input/elasticapm/internal/modeldecoder/v2/decoder.go:279 +0x193                                                                                                                                                                            
github.com/elastic/apm-data/input/elasticapm/internal/modeldecoder/v2.DecodeNestedMetadata(...)                                                                                                                                                                                   
        /home/andrew/projects/apm-data/input/elasticapm/internal/modeldecoder/v2/decoder.go:166                                          
github.com/elastic/apm-data/input/elasticapm.(*Processor).readMetadata(0xc000726070?, 0xc00064e010, 0xc00014e000?)                       
        /home/andrew/projects/apm-data/input/elasticapm/processor.go:126 +0x1d5                                                          
github.com/elastic/apm-data/input/elasticapm.(*Processor).HandleStream(0xc000726070, {0xf12c68, 0xc00041e090}, 0x1, 0xc000780000?, {0xf0c600, 0xc00014e000}, 0xc23d4c?, {0xf0a200, 0xc000322120}, ...)                                                                            
        /home/andrew/projects/apm-data/input/elasticapm/processor.go:274 +0x13a                                                          
github.com/elastic/apm-data/input/elasticapm.TestConcurrentAsync.func1.1.1()                                                             
        /home/andrew/projects/apm-data/input/elasticapm/processor_test.go:396 +0x1a5                                                     
created by github.com/elastic/apm-data/input/elasticapm.TestConcurrentAsync.func1.1                                                      
        /home/andrew/projects/apm-data/input/elasticapm/processor_test.go:393 +0x18c                                                     
FAIL    github.com/elastic/apm-data/input/elasticapm    0.225s
```

**Comment by kruskall** [comment]
> Are they disabled? It doesn't look like it. Did you revert a change, and forget to update the description?
> (I don't think we should disable them until we have replacement coverage.)

They are currently disabled (see https://github.com/elastic/apm-data/pull/67/files#diff-ce8c691488600b0f16281dec1b98c19dabd7edaa32cdc19df046a5829d23d9c4R93). I tried to fix them but found myself rewriting a large portion of the tests.
I don't like disabling them but I don't think they can be easily updated.

> I just ran the tests locally and got this panic:

*check notes* 

That's... not supposed to happen. I'll look into it

**Comment by axw** [comment]
>> I just ran the tests locally and got this panic:
>
> check notes
>
> That's... not supposed to happen. I'll look into it

It seems to be a data race -- try running with `-race`.

**Comment by kruskall** [comment]
Should be fixed!

**Comment by axw** [comment]
@kruskall can you please add `-race` to the `make test` target, so this kind of thing gets caught in CI?

Just having a look at the skipped reflection code now.

**Comment by axw** [comment]
@kruskall the skips can be removed by cherry-picking https://github.com/elastic/apm-data/commit/436bc1937084be4113e2ea4cc4ab854d80c2e1a7

**Comment by kruskall** [comment]
@axw Thank you! :bow: 

Some unrelated (semaphore) tests are failing when run with the race detector. I've opened a followup issue: https://github.com/elastic/apm-data/issues/68

**Review by axw — APPROVED** [review]

**Pull request merged**
