### PR TITLE
Centralize retrieving instrumentation scope framework conversion for all signals

### PR DESCRIPTION
**Pull request by Mpdreamz**
Addresses: #325

This PR ensures we map OpenTelemetry Instrumentation Scope to `Service.Framework.*` for all signal types.

### CODE REVIEW

**Review by lahsivjar — COMMENTED** [review]
LGTM! Can we add a test for metrics and logs (similar to https://github.com/elastic/apm-data/blob/20891800b4a7ea6e683a4aeae79f1b20541f23de/input/otlp/traces_test.go#L567-L579)?

**Review by simitt — CHANGES_REQUESTED** [review]
The PR is missing a description and a link to the issue it fixes.

**Comment by Mpdreamz** [comment]
I think metrics is already covered in the tests that I updated here: [`1d6ac13` (#339)](https://github.com/elastic/apm-data/pull/339/commits/1d6ac13d915d466de1926f0e150de87a3432ed01)

Added an additional test for logs @lahsivjar

**Review by lahsivjar — APPROVED** [review]
LGTM! Thanks for adding the tests.

**Comment by akhileshpok** [comment]
@lahsivjar - When will this enhancement become available for customers? Is it only applicable to MIS? Thanks

**Comment by akhileshpok** [comment]
@simitt - Wondering if you can help me with the timelines/release for availability of this enhancement! Thanks

**Comment by lahsivjar** [comment]
@akhileshpok Apologies about missing the previous ping, it fell through the cracks 😓 

> 
Hi @akhileshpok , apologies, I missed your previous message.
The change can be brought back to the next minor version of the apm-sever and also be brought back to the serverless offering.

> @lahsivjar could you cut a release for this and ensure that automation picks up the new version?

Will do!

**Comment by lahsivjar** [comment]
@akhileshpok @simitt [Here is the PR](https://github.com/elastic/apm-server/pull/13903) for adding the fix to APM-Server. It will be merged soon and should be available with `8.16.0` release.

**Pull request merged**
